apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 3
  template:
    metadata:
      name: nginx
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx
          image: nginx


#  1063  kubectl edit replicaset myapp-replicaset
#  1064  kubectl get pods
#  1065  kubectl scale replicaset myapp-replicaset --replicas=2
#  1066  kubectl delete replicaset myapp-replicaset
# devin@Devins-MBP replicasets % 
