apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: myapp
    type: front-end

spec: #RC spec
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: front-end

    spec: #pod spec
      containers:
        - name: nginx-container
          image: nginx
  replicas: 3
#  1014  kubectl create -f replication-con-definition.yml
#  1015  kubectl get pods
#  1016  kubectl get replicationcontroller
